workspace_root: &workspace_root
  ~/repo

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Compile artifacts
          command: npm run build
      - run:
          name: Package artifact
          command: npm pack
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Install code climate reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run test reporter
          command: ./cc-test-reporter before-build
      - run:
          name: Run jest
          command: npm test -- --coverage
      - run:
          name: Publish coverage
          command: ./cc-test-reporter after-build

  deploy-to-staging:
    <<: *defaults
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: *workspace_root
      - add_ssh_keys:
          fingerprints:
            - "47:1c:8b:3d:98:f9:c0:1c:7c:2d:77:e9:cd:46:da:cf"
      - run:
          name: Install python requirements
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install ansible vrun
      - run:
          name: Install ansible requirements
          command: ./.venv/bin/vrun ansible-galaxy install -r requirements.yml
      - run:
          name: Configure ansible inventory
          command: echo -e "[web]\n${STAGING_DEPLOY_HOST}" > inventory.yml
      - run:
          name: Deploy to Staging
          command: >
            env
            NODE_ENV="production"
            NODE_PORT="$STAGING_NODE_PORT"
            NODE_SERVER_NAME="$STAGING_NODE_SERVER_NAME"
            NODE_PROJECT_ENVIRONMENT="staging"
            NODE_ENV_CONFIG="NODE_GA_CODE=$STAGING_NODE_GA_CODE $STAGING_NODE_ENV_CONFIG"
            ./.venv/bin/vrun ansible-playbook deploy.yml -i inventory.yml

  deploy-to-production:
    <<: *defaults
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: *workspace_root
      - add_ssh_keys:
          fingerprints:
            - "47:1c:8b:3d:98:f9:c0:1c:7c:2d:77:e9:cd:46:da:cf"
      - run:
          name: Install python requirements
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install ansible vrun
      - run:
          name: Install ansible requirements
          command: ./.venv/bin/vrun ansible-galaxy install -r requirements.yml
      - run:
          name: Configure ansible inventory
          command: echo -e "[web]\n${PRODUCTION_DEPLOY_HOST}" > inventory.yml
      - run:
          name: Deploy to Production
          command: >
            env
            NODE_ENV="production"
            NODE_PORT="$PRODUCTION_NODE_PORT"
            NODE_SERVER_NAME="$PRODUCTION_NODE_SERVER_NAME"
            NODE_PROJECT_ENVIRONMENT="production"
            NODE_ENV_CONFIG="NODE_GA_CODE=$PRODUCTION_NODE_GA_CODE $PRODUCTION_NODE_ENV_CONFIG"
            ./.venv/bin/vrun ansible-playbook deploy.yml -i inventory.yml

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy-to-staging:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy-to-production:
          requires:
            - build
            - test
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
