export const FORM_GAME_DETAILS = 'FORM_GAME_DETAILS';
export const FORM_GAME_INSPIRATION = 'FORM_GAME_INSPIRATION';
export const FORM_INSPIRATION_SOURCE = 'FORM_INSPIRATION_SOURCE';
export const FORM_TEAM_DETAILS = 'FORM_TEAM_DETAILS';
