---
- name: Deploy to AWS
  hosts: web
  vars:
    node_project_id: 'cz-polocas-napadu-web'
    node_project_environment: '{{ lookup("env", "NODE_PROJECT_ENVIRONMENT") }}'

  roles:
    - role: practical-ansible.nginx_node
    - role: practical-ansible.nginx-redirect
      nginx_redirect_project_name: cz-polocas-napadu
      nginx_redirect_server_name: polocasnapadu.cz www.polocasnapadu.cz www.polocas-napadu.cz
      nginx_redirect_destination_domain: polocas-napadu.cz
