---
- name: Deploy to AWS
  hosts: web
  vars:
    node_project_id: 'cz-polocas-napadu-web'
    node_project_environment: '{{ lookup("env", "NODE_PROJECT_ENVIRONMENT") }}'

  roles:
    - role: practical-ansible.nginx_node
