workspace_root: &workspace_root
  ~/repo

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9-stretch

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
            - packages/referee/node_modules
            - packages/scoreboard/node_modules
          key: dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build_referee:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          working_directory: packages/referee
          name: Build artifacts
          command: npm run build

      - run:
          name: Copy artifact to root build folder
          command: |
            mkdir build
            cp -r packages/referee/build build/referee

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  build_scoreboard:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          working_directory: packages/scoreboard
          name: Build artifacts
          command: npm run build

      - run:
          name: Copy artifact to root build folder
          command: |
            mkdir build
            cp -r packages/scoreboard/build build/scoreboard

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  build_inspirations:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          working_directory: packages/inspirations
          name: Build artifacts
          command: npm run build

      - run:
          name: Copy artifact to root build folder
          command: |
            mkdir build
            cp -r packages/inspirations/build build/inspirations

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Run tests
          command: npm test -- --coverage

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3-stretch
    steps:
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync build s3://scoreboard.polocas-napadu.cz --delete

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build_inspirations:
          requires:
            - install
      - build_referee:
          requires:
            - install
      - build_scoreboard:
          requires:
            - install
      - deploy:
          requires:
            - test
            - build_inspirations
            - build_referee
            - build_scoreboard
          filters:
            branches:
              only: master
