---
name: Continuous deployment
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/website/deploy.yml
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get -y install python-docker python3-docker
          ansible-galaxy install -r requirements-ansible.yml
      - name: Buld core
        run: npm run build:core
      - name: Test
        run: npm test -- --coverage
      - name: Build website
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy-polocas-napadu-website:
    name: Deploy polocas napadu website
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/website/deploy.yml
      - name: Install dependencies
        run: |
          sudo apt-get -y install python-docker python3-docker
          ansible-galaxy install -r requirements-ansible.yml
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        env:
          NODE_SERVER_NAME: ${{ secrets.PRODUCTION_NODE_SERVER_NAME }}
          NODE_PROJECT_ENVIRONMENT: production
          NODE_API_URL: ${{ secrets.PRODUCTION_NODE_API_URL }}
          NODE_GA_CODE: ${{ secrets.PRODUCTION_NODE_GA_CODE }}
        run: |
          cp dist/polocas-napadu-website.tgz packages/website/
          cd ./packages/website
          echo -e "[web]\n${{ secrets.PRODUCTION_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy.yml -i inventory

  deploy-longforman-website:
    name: Deploy longforman website
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Install dependencies
        run: |
          sudo apt-get -y install python-docker python3-docker
          ansible-galaxy install -r requirements-ansible.yml
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/website/deploy.yml
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_LONGFORMAN_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_LONGFORMAN_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        env:
          NODE_SERVER_NAME: ${{ secrets.PRODUCTION_LONGFORMAN_NODE_SERVER_NAME }}
          NODE_PROJECT_ENVIRONMENT: production
          NODE_API_URL: ${{ secrets.PRODUCTION_LONGFORMAN_NODE_API_URL }}
          NODE_GA_CODE: ${{ secrets.PRODUCTION_LONGFORMAN_NODE_GA_CODE }}
        run: |
          cp dist/longforman-website.tgz packages/longforman-website/
          cd ./packages/longforman-website
          echo -e "[web]\n${{ secrets.PRODUCTION_LONGFORMAN_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy.yml -i inventory

  deploy-polocas-napadu-website-static:
    name: Deploy polocas napadu static media
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/website/deploy-static.yml
      - name: Install dependencies
        run: |
          sudo apt-get install rsync
          ansible-galaxy install -r requirements-ansible.yml
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        run: |
          cd ./packages/website
          echo -e "[web]\n${{ secrets.PRODUCTION_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy-static.yml -i inventory

  deploy-longforman-website-static:
    name: Deploy longforman website static media
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/longforman-website/deploy-static.yml
      - name: Install dependencies
        run: ansible-galaxy install -r requirements-ansible.yml
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_LONGFORMAN_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_LONGFORMAN_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        run: |
          cd ./packages/longforman-website
          echo -e "[web]\n${{ secrets.PRODUCTION_LONGFORMAN_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy-static.yml -i inventory
