name: Continuous deployment
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  deploy-website-production:
    name: Deploy production website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/polocas-napadu-website/deploy.yml
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get -y install python-docker python3-docker
          ansible-galaxy install -r requirements-ansible.yml
      - name: Test
        run: npm test -- --coverage
      - name: Build website
        run: npm run build-website
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        env:
          NODE_SERVER_NAME: ${{ secrets.PRODUCTION_NODE_SERVER_NAME }}
          NODE_PROJECT_ENVIRONMENT: production
          NODE_API_URL: ${{ secrets.PRODUCTION_NODE_API_URL }}
          NODE_GA_CODE: ${{ secrets.PRODUCTION_NODE_GA_CODE }}
        run: |
          cd ./packages/polocas-napadu-website
          echo -e "[web]\n${{ secrets.PRODUCTION_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy.yml -i inventory

  deploy-redirects:
    name: Deploy production website redirects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: ansible/ansible-lint-action@master
        with:
          targets: packages/polocas-napadu-website/deploy-static.yml
      - name: Install dependencies
        run: ansible-galaxy install -r requirements-ansible.yml
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        run: |
          cd ./packages/polocas-napadu-website
          echo -e "[web]\n${{ secrets.PRODUCTION_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy-static.yml -i inventory
