name: Continuous integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: Run tests on all packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --coverage

  build:
    name: Build all packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build the packages
        run: ./node_modules/.bin/lerna run build

  deploy-staging:
    name: Deploy staging website
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            packages/polocas-napadu-website/deploy.yml
            packages/polocas-napadu-website/deploy-static.yml
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get -y install python-docker python3-docker
          ansible-galaxy install -r requirements-ansible.yml
      - name: Build
        run: npm run build-website
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.STAGING_WEBSITE_KNOWN_HOSTS }}
      - name: Deploy app
        env:
          NODE_SERVER_NAME: ${{ secrets.STAGING_NODE_SERVER_NAME }}
          NODE_PROJECT_ENVIRONMENT: staging
          NODE_API_URL: ${{ secrets.STAGING_NODE_API_URL }}
        run: |
          cd ./packages/polocas-napadu-website
          echo -e "[web]\n${{ secrets.STAGING_WEBSITE_DEPLOY_HOST }}\n" > inventory
          ansible-playbook deploy.yml -i inventory
